name: Deploy to Azure Web App

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: 
      - main
      
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'outdoor-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cbb23b28776b4fd5a5918012ec3ca316 }}
        images: 'outdoorcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_08fc9bd893ac490ba300f65cecb0d2c0 }}/outdoor-api:${{ github.sha }}'