name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://outdoorcontainer.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_08fc9bd893ac490ba300f65cecb0d2c0 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6b60371bf6a942d7a6d17e9e59d3a53f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: outdoorcontainer.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_08fc9bd893ac490ba300f65cecb0d2c0 }}/outdoor-api:${{ github.sha }}
        file: ./Dockerfile

    - name: Unit Tests
      run: dotnet test
